/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-container": "#1f1f1f",
        "background": "#131313",
        "tertiary-fixed": "#e2e2e2",
        "on-primary-container": "#636565",
        "primary": "#ffffff",
        "surface-container-highest": "#353535",
        "surface-variant": "#353535",
        "on-primary-fixed": "#1a1c1c",
        "tertiary-container": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "error": "#ffb4ab",
        "on-secondary": "#2f3038",
        "on-tertiary-fixed": "#1a1c1c",
        "secondary-fixed": "#e3e1ec",
        "surface-tint": "#c6c6c7",
        "on-tertiary": "#2f3131",
        "primary-fixed-dim": "#c6c6c7",
        "surface-elevated": "#121214",
        "on-surface-variant": "#c4c7c8",
        "on-primary": "#2f3131",
        "warning-gray": "#a1a1aa",
        "on-tertiary-fixed-variant": "#454747",
        "surface-dim": "#131313",
        "secondary-fixed-dim": "#c6c5cf",
        "tertiary": "#ffffff",
        "on-primary-fixed-variant": "#454747",
        "primary-container": "#e2e2e2",
        "inverse-on-surface": "#303030",
        "primary-fixed": "#e2e2e2",
        "error-container": "#93000a",
        "inverse-primary": "#5d5f5f",
        "surface-container-lowest": "#0e0e0e",
        "on-error": "#690005",
        "secondary": "#c6c5cf",
        "surface-bright": "#393939",
        "surface-deep": "#09090b",
        "surface-container-low": "#1b1b1b",
        "success-white": "#ffffff",
        "inverse-surface": "#e2e2e2",
        "border-muted": "#27272a",
        "text-muted": "#a1a1aa",
        "outline": "#8e9192",
        "surface": "#131313",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#bcbbc5",
        "outline-variant": "#444748",
        "on-secondary-fixed": "#1a1b22",
        "on-tertiary-container": "#636565",
        "on-secondary-fixed-variant": "#46464e",
        "on-background": "#e2e2e2",
        "surface-container-high": "#2a2a2a",
        "secondary-container": "#4a4b53",
        "on-surface": "#e2e2e2"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "16px",
        "panel-gap": "1px",
        "unit": "4px",
        "margin-desktop": "24px",
        "margin-mobile": "12px"
      },
      "fontFamily": {
        "body-md": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"]
      },
      "fontSize": {
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "code-sm": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.04em", "fontWeight": "600"}],
        "body-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "headline-md": ["20px", {"lineHeight": "1.4", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-caps": ["10px", {"lineHeight": "12px", "letterSpacing": "0.1em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
